#!/usr/bin/env python3
"""Generate OKR/KR progress report for AZURECLIPS project."""

import json
import subprocess
import sys
from datetime import datetime, timezone

OWNER = "Alex-AZPS"
REPO = "alex-repo"
PROJECT_NUMBER = 1

KR_MAP = [
    {"kr": "KR1.1", "epic_number": 11},
    {"kr": "KR1.2", "epic_number": 9},
    {"kr": "KR2.1", "epic_number": 12},
    {"kr": "KR2.2", "epic_number": 15},
    {"kr": "KR3.1", "epic_number": 18},
]

def run_graphql(query):
    result = subprocess.run(
        ["gh", "api", "graphql", "-f", f"query={query}"],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"GraphQL error: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    return json.loads(result.stdout)

def get_epic_data(epic_number):
    query = '''
    query {
      repository(owner: "%s", name: "%s") {
        issue(number: %d) {
          number
          title
          state
          url
          subIssues(first: 50) {
            totalCount
            nodes {
              number
              title
              state
              labels(first: 10) { nodes { name } }
            }
          }
        }
      }
    }
    ''' % (OWNER, REPO, epic_number)
    data = run_graphql(query)
    return data["data"]["repository"]["issue"]

def generate_report():
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = []
    lines.append("<!-- OKR_REPORT_START -->")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"> Last updated: **{now}** | Auto-generated by GitHub Actions")
    lines.append("")
    lines.append("| KR | Epic | KR % | Features (closed/total) | Tasks (closed/total) | Completed | Plan |")
    lines.append("|:---:|:----:|:----:|:-----------------------:|:--------------------:|-----------|------|")

    for kr_info in KR_MAP:
        kr_label = kr_info["kr"]
        epic = get_epic_data(kr_info["epic_number"])
        subs = epic.get("subIssues", {}).get("nodes", [])

        features = [s for s in subs if "[Feature]" in s.get("title", "")]
        tasks = [s for s in subs if "[Feature]" not in s.get("title", "")]

        feat_closed = sum(1 for f in features if f["state"] == "CLOSED")
        feat_total = len(features)
        feat_pct = f"{100 * feat_closed // feat_total}%" if feat_total > 0 else "0%"

        task_closed = sum(1 for t in tasks if t["state"] == "CLOSED")
        task_total = len(tasks)

        total = feat_total + task_total
        done = feat_closed + task_closed
        kr_pct = f"{100 * done / total:.1f}%" if total > 0 else "0%"

        completed = [f"#{s['number']} {s['title']}" for s in subs if s["state"] == "CLOSED"]
        completed_str = "; ".join(completed) if completed else "*(none yet)*"

        plan = [f"#{s['number']} {s['title']}" for s in subs if s["state"] == "OPEN"]
        plan_str = "; ".join(plan) if plan else "*(all done!)*"

        lines.append(
            f"| {kr_label} | [#{epic['number']}]({epic['url']}) "
            f"| **{kr_pct}** | {feat_closed}/{feat_total} ({feat_pct}) "
            f"| {task_closed}/{task_total} "
            f"| {completed_str} | {plan_str} |"
        )

    lines.append("")
    lines.append("<!-- OKR_REPORT_END -->")
    return "\n".join(lines)

def update_readme(report):
    with open("README.md", "r", encoding="utf-8") as f:
        content = f.read()

    start_marker = "<!-- OKR_REPORT_START -->"
    end_marker = "<!-- OKR_REPORT_END -->"

    if start_marker in content:
        before = content[:content.index(start_marker)]
        after = content[content.index(end_marker) + len(end_marker):]
        content = before + report + after
    else:
        content = content.rstrip() + "\n\n" + report + "\n"

    with open("README.md", "w", encoding="utf-8") as f:
        f.write(content)

    # Also update the project README via GraphQL
    escaped = report.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

    # Get current project readme
    q = 'query { user(login: "%s") { projectV2(number: %d) { id readme } } }' % (OWNER, PROJECT_NUMBER)
    data = run_graphql(q)
    pid = data["data"]["user"]["projectV2"]["id"]
    cur = data["data"]["user"]["projectV2"]["readme"] or ""

    if start_marker in cur:
        before = cur[:cur.index(start_marker)]
        after = cur[cur.index(end_marker) + len(end_marker):]
        new_readme = before + report + after
    else:
        new_readme = cur.rstrip() + "\n\n" + report + "\n"

    esc = new_readme.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    mutation = 'mutation { updateProjectV2(input: {projectId: "%s", readme: "%s"}) { projectV2 { url } } }' % (pid, esc)
    run_graphql(mutation)

    print("README.md and Project README updated with OKR report")

if __name__ == "__main__":
    report = generate_report()
    update_readme(report)