#!/usr/bin/env python3
"""Generate OKR/Epic progress report for AZURECLIPS project."""

import json
import subprocess
import sys
from datetime import datetime, timezone

PROJECT_NUMBER = 1
OWNER = "Alex-AZPS"

def run_graphql(query):
    result = subprocess.run(
        ["gh", "api", "graphql", "-f", f"query={query}"],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"GraphQL error: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    return json.loads(result.stdout)

def get_epics():
    query = '''
    query {
      user(login: "%s") {
        projectV2(number: %d) {
          items(first: 100) {
            nodes {
              content {
                ... on Issue {
                  number
                  title
                  state
                  url
                  labels(first: 10) { nodes { name } }
                  subIssues(first: 50) {
                    totalCount
                    nodes {
                      number
                      title
                      state
                      labels(first: 5) { nodes { name } }
                    }
                  }
                }
              }
              fieldValues(first: 10) {
                nodes {
                  ... on ProjectV2ItemFieldSingleSelectValue {
                    field { ... on ProjectV2SingleSelectField { name } }
                    name
                  }
                }
              }
            }
          }
        }
      }
    }
    ''' % (OWNER, PROJECT_NUMBER)
    return run_graphql(query)

def make_progress_bar(pct, width=20):
    filled = int(width * pct / 100)
    empty = width - filled
    bar = "" * filled + "" * empty
    return bar

def get_field_value(item, field_name):
    for fv in item.get("fieldValues", {}).get("nodes", []):
        field = fv.get("field", {})
        if field and field.get("name") == field_name:
            return fv.get("name", "")
    return ""

def generate_report():
    data = get_epics()
    items = data["data"]["user"]["projectV2"]["items"]["nodes"]

    epics = []
    for item in items:
        content = item.get("content")
        if not content:
            continue
        sub_issues = content.get("subIssues", {})
        total = sub_issues.get("totalCount", 0)
        if total == 0:
            continue

        subs = sub_issues.get("nodes", [])
        done = sum(1 for s in subs if s.get("state") == "CLOSED")
        pct = (done * 100) // total if total > 0 else 0

        labels = [l["name"] for l in content.get("labels", {}).get("nodes", [])]
        squad = next((l for l in labels if l.startswith("act-")), "general")
        priority = get_field_value(item, "Priority")
        status = get_field_value(item, "Status")

        epics.append({
            "title": content["title"],
            "number": content["number"],
            "url": content["url"],
            "state": content["state"],
            "total": total,
            "done": done,
            "pct": pct,
            "squad": squad,
            "priority": priority,
            "status": status,
            "subs": subs,
        })

    # Sort by priority then completion
    priority_order = {"P0": 0, "P1": 1, "P2": 2, "P3": 3, "": 9}
    epics.sort(key=lambda e: (priority_order.get(e["priority"], 9), -e["pct"]))

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Calculate overall stats
    total_items = sum(e["total"] for e in epics)
    done_items = sum(e["done"] for e in epics)
    overall_pct = (done_items * 100) // total_items if total_items > 0 else 0

    lines = []
    lines.append("<!-- OKR_REPORT_START -->")
    lines.append("##  OKR / Epic Progress Report")
    lines.append("")
    lines.append(f"> Last updated: **{now}** | Auto-generated by GitHub Actions")
    lines.append("")
    lines.append("### Overall Progress")
    lines.append("")
    lines.append(f"`{make_progress_bar(overall_pct)}` **{overall_pct}%** ({done_items}/{total_items} items completed)")
    lines.append("")
    lines.append("### Epic Breakdown")
    lines.append("")
    lines.append("| Priority | Epic | Progress | Status | Squad |")
    lines.append("|:--------:|------|----------|:------:|-------|")

    for e in epics:
        bar = make_progress_bar(e["pct"], 10)
        emoji = "" if e["priority"] == "P0" else "" if e["priority"] == "P1" else "" if e["priority"] == "P2" else ""
        status_emoji = "" if e["status"] == "Done" else "" if e["status"] == "In Progress" else ""
        squad_name = e["squad"].replace("act-", "").replace("-", " ").title()
        lines.append(
            f"| {emoji} {e['priority']} "
            f"| [#{e['number']}]({e['url']}) {e['title']} "
            f"| `{bar}` {e['pct']}% ({e['done']}/{e['total']}) "
            f"| {status_emoji} {e['status']} "
            f"| {squad_name} |"
        )

    lines.append("")
    lines.append("### Detailed Breakdown")
    lines.append("")

    for e in epics:
        emoji = "" if e["priority"] == "P0" else "" if e["priority"] == "P1" else "" if e["priority"] == "P2" else ""
        lines.append(f"<details>")
        lines.append(f"<summary>{emoji} <b>{e['title']}</b>  {e['pct']}% ({e['done']}/{e['total']})</summary>")
        lines.append("")
        lines.append("| # | Sub-Issue | Status |")
        lines.append("|---|-----------|--------|")
        for s in e["subs"]:
            state_icon = "" if s["state"] == "CLOSED" else ""
            lines.append(f"| #{s['number']} | {s['title']} | {state_icon} |")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    lines.append("<!-- OKR_REPORT_END -->")

    return "\n".join(lines)

def update_readme(report):
    with open("README.md", "r", encoding="utf-8") as f:
        content = f.read()

    start_marker = "<!-- OKR_REPORT_START -->"
    end_marker = "<!-- OKR_REPORT_END -->"

    if start_marker in content:
        before = content[:content.index(start_marker)]
        after = content[content.index(end_marker) + len(end_marker):]
        content = before + report + after
    else:
        content = content.rstrip() + "\n\n" + report + "\n"

    with open("README.md", "w", encoding="utf-8") as f:
        f.write(content)

    print("README.md updated with OKR report")

if __name__ == "__main__":
    report = generate_report()
    update_readme(report)